config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route for home page
  get "/", to: "pages#home", as: "root"
  get "/info", to: "pages#info", as: "info" 
  
  #routes for listings
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/new/confirm", to: "listings#confirm_new", as: "confirm_new_listing"
  get "/listings/:id/buy", to: "listings#buy", as: "buy_listing"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#delete"

  #routes for profiles
  get "/profile", to: "profiles#show", as: "profile"
  put "/profile", to: "profiles#update"
  patch "/profile", to: "profiles#update"
  get "/profile/edit", to: "profiles#edit", as: "edit_profile"
  get "/profile/my_listings", to: "profiles#my_listings", as: "my_listings"

  #routes for payments
  get "/payments/success", to: "payments#success", as: "successful_payment"
  post "/payments/webhook", to: "payments#webhook"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    
    def show
        @user = current_user
    end

    def edit
        @user = current_user
    end

    def update
        whitelisted_user_params = params.require(:user).permit(:name, :alias, :email)
        whitelisted_address_params = params.require(:address).permit(:address, :suburb, :city, :country, :postcode)
        whitelisted_image = params.require(:user).permit(:image)

        current_user.update(whitelisted_user_params)

        current_user.update(image: params[:user][:image]) if params[:user][:image]

        if current_user.address.nil?
            current_user.create_address(whitelisted_address_params)
        else
            current_user.address.update(whitelisted_address_params)
        end
        redirect_to(profile_path)
    end

    def my_listings
        #get an array of the user's listing ids
        listings_ids = current_user.listings.ids

        #get an array of the sold items listing ids
        sold_ids = Purchase.purchase_ids

        #subtract them to get array of ids for items sold by this user which are still available
        still_available = listings_ids - sold_ids
        
        #passing only listings owned by the user which are still available to the view
        @my_listings = Listing.find(still_available)
        
        #creating the array of sold items
        list_of_sales = Listing.where(user_id: current_user.id).ids & Purchase.purchase_ids
        @sold = Listing.find(list_of_sales)

        #creating the array of purchased items
        list_of_purchases = current_user.purchases.map { |i| i.listing_id }
        @purchased = Listing.find(list_of_purchases)

        @purchases = Purchase.all
        @cards = Card.all
    end
end

app/views/profiles/edit.html.erb
<div id="edit-profile">
    <% @title = "Edit profile" %>
    <%= render "partials/top_bar" %>

    <h1>Edit your profile</h1>
    <div class="flex-col">
        <%= form_with(model: @user, url: profile_path, method: "put", local: true) do |user_form| %>
            <div>
                <%= user_form.label :name %>
                <%= user_form.text_field :name %>
            </div>
            <div>
                <%= user_form.label :alias %>
                <%= user_form.text_field :alias %>
            </div>
            <div>
                <%= user_form.label :email %>
                <%= user_form.text_field :email %>
            </div>
            <%= fields_for :address, @user.address do |address_form| %>
                <div>
                    <%= address_form.label :address %>
                    <%= address_form.text_field :address %>
                </div>
                <div>
                    <%= address_form.label :suburb %>
                    <%= address_form.text_field :suburb %>
                </div>
                <div>
                    <%= address_form.label :city %>
                    <%= address_form.text_field :city %>
                </div>
                <div>
                    <%= address_form.label :country %>
                    <%= address_form.text_field :country %>
                </div>
                <div>
                    <%= address_form.label :postcode %>
                    <%= address_form.text_field :postcode %>
                </div>
            <% end %>
            <div>
                <%= user_form.label :image %>
                <%= user_form.file_field :image, accept: "image/png, image/jpeg, image/jpg" %>
            </div>
            <%= user_form.submit value="Update", class: "button" %>
        <% end %>
    </div>
</div>

app/views/profiles/my_listings.html.erb
<div id="my-listings">
    <% @title = "My listings" %>
    <%= render "partials/top_bar" %>

    <h1>My listings</h1>

    <h3>Active listings</h3>
    <table>
        <thead>
            <tr>
                <th class="table_left-align">Card</th>
                <th>Set</th>
                <th>Price</th>
                <th>Date listed</th>
            </tr>
        </thead>
        <tbody>
            <% @my_listings.each { |listing| %>
                <tr>
                    <td class="table_left-align"><%= link_to(@cards.find(listing.card_id).name, listing_path(listing.id)) %></td>
                    <td><%= @cards.find(listing.card_id).set %></td>
                    <td><%= number_to_currency(listing.price / 100.0) %></td>
                    <td><%= listing.created_at.to_s[0..9] %></td>
                </tr>
            <% } %>
        </tbody>
    </table>

    <h3>Sold</h3>
    <table>
        <thead>
            <tr>
                <th class="table_left-align">Card</th>
                <th>Set</th>
                <th>Price</th>
                <th>Date sold</th>
            </tr>
        </thead>
        <tbody>
            <% @sold.each { |listing| %>
                <tr>
                    <td class="table_left-align"><%= @cards.find(listing.card_id).name %></td>
                    <td><%= @cards.find(listing.card_id).set %></td>
                    <td><%= number_to_currency(listing.price / 100.0) %></td>
                    <td><%= @purchases.find_by_listing_id(listing.id).created_at.to_s[0..9] %></td>
                </tr>
            <% } %>
        </tbody>
    </table>

    <h3>Purchased</h3>
    <table>
        <thead>
            <tr>
                <th class="table_left-align">Card</th>
                <th>Set</th>
                <th>Price</th>
                <th>Date purchased</th>
            </tr>
        </thead>
        <tbody>
            <% @purchased.each { |listing| %>
                <tr>
                    <td class="table_left-align"><%= @cards.find(listing.card_id).name %></td>
                    <td><%= @cards.find(listing.card_id).set %></td>
                    <td><%= number_to_currency(listing.price / 100.0) %></td>
                    <td><%= @purchases.find_by_listing_id(listing.id).created_at.to_s[0..9] %></td>
                </tr>
            <% } %>
        </tbody>
    </table>
</div>

app/views/profiles/show.html.erb
<div id="show-profile">
    <% @title = "Profile" %>
    <%= render "partials/top_bar" %>

    <h1>Your profile</h1>

    <div class="flex-container">
        <%= image_tag @user.image if @user.image.attached? %>

        <div class="flex-col">
            <%= link_to('<button type="button">Edit profile</button>'.html_safe, edit_profile_path) %>

            <%= link_to('<button type="button">Create new listing</button>'.html_safe, new_listing_path) %>

            <%= link_to('<button type="button">My listings</button>'.html_safe, my_listings_path) %>
        </div>
    </div>

    <div class="flex-centered">
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>   
                    <td>Name:</td>
                    <td><%= @user.name if @user %></td>
                </tr>
                <tr>   
                    <td>Alias:</td>
                    <td><%= @user.alias if @user %></td>
                </tr>
                <tr>   
                    <td>Address:</td>
                    <td><%= @user.address.address if @user.address %></td>
                </tr>
                <tr>   
                    <td></td>
                    <td><%= @user.address.suburb if @user.address %></td>
                </tr>
                <tr>   
                    <td></td>
                    <td><%= @user.address.city if @user.address %></td>
                </tr>
                <tr>   
                    <td></td>
                    <td><%= @user.address.country if @user.address %></td>
                </tr>
                <tr>   
                    <td></td>
                    <td><%= @user.address.postcode if @user.address %></td>
                </tr>
                <tr>   
                    <td>Email:</td>
                    <td><%= @user.email if @user %></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>