config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route for home page
  get "/", to: "pages#home", as: "root"
  get "/info", to: "pages#info", as: "info" 
  
  #routes for listings
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/new/confirm", to: "listings#confirm_new", as: "confirm_new_listing"
  get "/listings/:id/buy", to: "listings#buy", as: "buy_listing"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#delete"

  #routes for profiles
  get "/profile", to: "profiles#show", as: "profile"
  put "/profile", to: "profiles#update"
  patch "/profile", to: "profiles#update"
  get "/profile/edit", to: "profiles#edit", as: "edit_profile"
  get "/profile/my_listings", to: "profiles#my_listings", as: "my_listings"

  #routes for payments
  get "/payments/success", to: "payments#success", as: "successful_payment"
  post "/payments/webhook", to: "payments#webhook"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :card
  has_one :purchase
  validates :condition, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 100 }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    #called when user clicks "Browse" in the top bar
    #sends data to listings/index.html.erb
    def index
         if params[:search]
            #eager loading the cards associated with the listings
            #then nested eager load the images associated with those cards
            listings = Listing.includes(card: {image_attachment: :blob}).all
            
            #calling a custom method 'purchase_ids' on the purchase model to return an array of purchase ids
            purchases = Purchase.purchase_ids
    
            listings_available = listings.ids - purchases
    
            search = "%#{params[:search]}%"
            
            #calling a custom method 'search' on Card called to find records matching the name input
            @listings = listings.where(id: listings_available).where(card_id: Card.search(search).ids).uniq { |l| l.card_id }
        else
            #eager loading the purchases and cards with their attached images
            listings = Listing.includes(:purchase, card: {image_attachment: :blob}).all

            #removing the listings which have been purchased from the available listings
            listings_records = []
            listings.each { |listing| 
                listings_records.push(listing) unless listing.purchase
            }

            @listings = listings_records.uniq { |l| l.card_id }
        end
    end

    #called when user clicks a card on listings/index.html.erb
    #sends data to listings/show.html.erb
    def show
        #query to find listing to show
        #eager load the card associated with the listing
        #then nested eager load the listings associated with that card
        @listing = Listing.includes(card: :listings).find(params[:id])

        #get all ids of listings of this card
        listings_ids = @listing.card.listings.ids

        #get the listing ids of sold listings
        purchases_ids = Purchase.purchase_ids

        #calculate the list of ids for available listings
        listings_available_ids = listings_ids - purchases_ids

        #get the list of records for available listing
        @listings = Listing.where(id: listings_available_ids)
    end

    #called when user clicks "Buy" on the show page
    #sends data to listings/buy.html.erb. 
    def buy
        #query to find listing to buy
        @listing = Listing.find(params[:id])

        #query to find the image attached to the card attached to the listing
        @card_image = @listing.card.image
        
        #query to find the name attached to the card attached to the listing
        card_name = @listing.card.name

        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.email,
            line_items: [{
                name: card_name,
                amount: @listing.price,
                images: [@listing.card.imageUrl],
                currency: 'aud',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    user_id: current_user.id,
                    listing_id: @listing.id
                }
            },
            success_url: "#{root_url}payments/success",
            cancel_url: "#{root_url}listings"
        )
    
        @session_id = session.id
    end

    #called when user clicks "Search" on listings/new.html.erb
    #sends data to listings/new.html.erb
    def new
        #get an empty record of Card to send to the view
        @card = Card.new

        if params[:card]
            #query to find a card with a specific name and set a per our search
            @cards = Card.where(name: params[:card][:name]).where(set: params[:card][:set])
        else
            #if there is no search, there is nothing to render, send nil
            @cards = nil
        end
    end

    #called when user clicks "Yes" button on listings/new => new.html.erb
    #sends data to listings/confirm.html.erb
    def confirm_new
        #query to find the correct record to send to the view
        @card = Card.find(params[:card][:id])
        @empty_search = params[:empty_search]
    end

    #called with "Create listing" button on /listings/new/confirm => confirm.html.erb
    #enters the new listing into the database
    def create
        #if the user does not enter the condition or price fields, reload the page
        if params[:listing][:condition].empty? || params[:listing][:price].empty?
            redirect_to confirm_new_listing_path(card: {id: params[:listing][:card_id]}, empty_search: true)
        else
            whitelisted_params = params.require(:listing).permit(:condition, :price, :card_id)
            current_user.listings.create(whitelisted_params)
            redirect_to(listings_path)
        end
    end

    def edit
        #query to find the correct listing to send to the view
        #eager loading the card associated with the listing
        #then nested eager load the image associated with that card
        @listing = Listing.find(params[:id])

        #do not allow access to the edit page of a card that is already purchased
        #instead redirect to listings
        if @listing.purchase
            redirect_to listings_path and return
        end

        @card_image = @listing.card.image

        if current_user.id != @listing.user.id
            redirect_to listings_path
        end
    end

    #called when "Update listing" button is pressed on /listings/:id => listings/show.html.erb
    #updated record for the relevant listing
    def update
        #query to find the correct listing to update
        listing = Listing.find(params[:id])
        
        whitelisted_params = params.require(:listing).permit(:condition, :price)
        listing.update(whitelisted_params)
        redirect_to(listing_path(params[:id]))
    end

    #called when "Delete" button is pressed on /listings/:id => listings/show.html.erb
    #deletes record for the relevant listing
    def delete
        #query to find the correct listing to delete
        Listing.find(params[:id]).destroy
        redirect_to(listings_path)
    end
end

app/views/listings/buy.html.erb
<div id="buy">
  <% @title = "Buy" %>
  <%= render "partials/top_bar" %>

  <h1>You are about to purchase the following card</h1>

  <div class="flex-container">
  
    <%= image_tag @card_image %>

    <div class="flex-col">
      <p><%= number_to_currency(@listing.price / 100.0) %></p>
      
      <form method="POST" action="<%= buy_listing_path %>">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
          <input type="hidden" name="id" value="<%= @listing.id %>" />
          <input data-stripe="payment" type=submit value="Confirm" class="button" />
      </form>
    </div>
  </div>
</div>

<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>

app/views/listings/confirm.html.erb
<%= render "partials/top_bar" %>

<h1>You are about to list the following card</h1>

<%= image_tag @card.image %>

<form method="POST" action="<%= listings_path %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <div>
        <label for="condition">Condition</label>
        <input type="text" name="listing[condition]" id="condition" />
    </div>
    <div>
        <label for="price">Price</label>
        <input type="float" name="listing[price]" id="price" />
    </div>
    <input type="hidden" name="listing[card_id]" value=<%= @card.id %> />
    <input type="submit" value="Create listing" />
</form>

app/views/listings/confirm_new.html.erb
<div id="confirm-new">
    <% @title = "Confirm new" %>
    <%= render "partials/top_bar" %>

    <h1>You are about to list the following card</h1>

    <div class="flex-container">
        <%= image_tag @card.image %>

        <div class="flex-col">
            <form method="POST" action="<%= listings_path %>">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                <p><%= "Please fill in the details for your listing" if @empty_search %></p>
                <div>
                    <label for="condition">Condition</label>
                    <input type="text" name="listing[condition]" id="condition" />
                </div>
                <div>
                    <label for="price">Price</label>
                    <input type="float" name="listing[price]" id="price" />
                </div>
                <input type="hidden" name="listing[card_id]" value=<%= @card.id %> />
                <input type="submit" value="Create listing" class="button" />
            </form>
        </div>
    </div>
</div>

app/views/listings/edit.html.erb
<div id="edit"> 
    <% @title = "Edit listing" %>
    <%= render "partials/top_bar" %>

    <h1>Edit listing</h1>

    <div class="flex-container">
        <%= image_tag @card_image %>

        <%= form_with(model: @listing, local: true) do |form| %>
            <div class="flex-col">
                <div>
                    <%= form.label :condition %>
                    <%= form.text_field :condition %>
                </div>
                <div>
                    <%= form.label :price %>
                    <%= form.text_field :price %>
                </div>
                <%= form.submit class: "button" %> 
            </div>
        <% end %>
    </div>
</div>

app/views/listings/index.html.erb
<div id="index">
    <% @title = "Browse" %>
    <%= render "partials/top_bar" %>

    <h3>Search</h3>

    <div class="filter">
        <%= form_with(url: listings_path, method: "get", local: true) do |form| %>
            <div class="filter">
                <div>
                    <%= form.text_field(:search) %>
                </div>
                <%= form.submit "Search", class: "button" %>
            </div>
        <% end %>
    </div>

    <div class="cards-container">
        <% @listings.each_with_index { |listing, index| %>
            <%= link_to listing_path(@listings[index].id), action: 'go' do %>
                <div class="card">
                    <%= image_tag listing.card.image if listing.card.image.attached? %>
                </div>
            <% end %>
        <% } %>
    </div>
</div>

app/views/listings/new.html.erb
<div id="new-listing">
    <% @title = "New listing" %>
    <%= render "partials/top_bar" %>

    <h1>Enter the details for the card you wish to list</h1>

    <div class="flex-col">
        <%= form_with(model: @card, url: new_listing_path, method: "get", local: true) do |form| %>
            <div>
                <%= form.label(:name) %>
                <%= form.text_field(:name) %>
            </div>
            <div>
                <%= form.label(:set) %>
                <%= form.text_field(:set) %>
            </div>
                <%= submit_tag "Search", class: "button" %>
        <% end %>

        <% if @cards %>
            <% if @cards.empty? %>
                <p><%= "There were no cards that matched your search" %></p>
            <% else %>
                <%= link_to confirm_new_listing_path, action: 'go' do %>
                    <div>
                        <%= image_tag @cards[0].image if @cards[0].image.attached? %>
                    </div>
                <% end %>
                <h3>Continue to enter listing details</h3>
                <form method="GET" action="<%= confirm_new_listing_path %>">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                    <input type="hidden" name="card[id]" value="<%= @cards[0].id %>" />
                    <input class="button" type="submit" value="Continue" />
                </form>
            <% end %>
        <% end %>
    </div>
</div>

app/views/listings/show.html.erb
<div id="show">
    <% @title = @listing.card.name %>
    <%= render "partials/top_bar" %>

    <h1><%= @listing.card.name %></h1>

    <div class="flex-container">
        <%= image_tag @listing.card.image if @listing.card.image.attached? %>

        <div>
            <table>
                <thead>
                    <tr>
                        <th class="table_left-align">Seller</th>
                        <th>Condition</th>
                        <th>Price</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @listings.each { |listing| %>
                        <tr>
                            <td class="table_left-align"><%= listing.user.email %></td>
                            <td><%= listing.condition %></td>
                            <td><%= number_to_currency(listing.price / 100.0) %></td>
                            <td>
                                <% if current_user.nil? || listing.user_id != current_user.id %>
                                    <%= link_to('<button type="button">Buy</button>'.html_safe, buy_listing_path(listing.id)) %>
                                <% end %>
                            </td>
                            <td>
                                <% if current_user && listing.user_id == current_user.id %>
                                    <%= link_to('<button type="button">Edit</button>'.html_safe, edit_listing_path(listing.id)) %>
                                <% end %>
                            </td>
                            <td>
                                <% if current_user && listing.user_id == current_user.id %>
                                    <%= form_with(url: listing_path, method: "delete") do %>
                                        <%= submit_tag "Delete", class: "delete-button"  %>
                                    <% end %>
                                <% end %>
                            </td>
                        </tr>
                    <% } %>
                </tbody>
            </table>
        </div>
    </div>
</div>