config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route for home page
  get "/", to: "pages#home", as: "root"
  get "/info", to: "pages#info", as: "info" 
  
  #routes for listings
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/new/confirm", to: "listings#confirm_new", as: "confirm_new_listing"
  get "/listings/:id/buy", to: "listings#buy", as: "buy_listing"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#delete"

  #routes for profiles
  get "/profile", to: "profiles#show", as: "profile"
  put "/profile", to: "profiles#update"
  patch "/profile", to: "profiles#update"
  get "/profile/edit", to: "profiles#edit", as: "edit_profile"
  get "/profile/my_listings", to: "profiles#my_listings", as: "my_listings"

  #routes for payments
  get "/payments/success", to: "payments#success", as: "successful_payment"
  post "/payments/webhook", to: "payments#webhook"
end

app/views/pages/home.html.erb
<div id="home">
    <% @title = "Home" %>

    <%= render "partials/top_bar" %>

    <h1>MTG-marketplace</h1>
    <div class="flex-container">
        <%= link_to info_path, action: "go" do %>
            <div class="flex-centered">
                <%= image_tag 'peer-to-peer bw.png', class: "img-margin" %> 
                <p>Peer-to-peer</p>
            </div>
        <% end %>
        <%= link_to info_path, action: "go" do %>
            <div class="flex-centered">
                <%= image_tag 'handshake.png', class: "img-margin" %> 
                <p>Easy to buy and sell</p>
            </div>
        <% end %>
        <%= link_to info_path, action: "go" do %>
            <div class="flex-centered">
                <%= image_tag 'lock.png', class: "img-margin" %> 
                <p>Secure</p>
            </div>
        <% end %>
    </div>
</div>

app/views/pages/info.html.erb
<div id="info">
    <% @title = "Info" %>
    <%= render "partials/top_bar" %>

    <h1>Information</h1>

    <h2>What is MTG-marketplace?</h2>
    <p>MTG-marketplace is an online shop for Magic: The Gathering cards.</p>
    <p>The sales are all peer-to-peer. This means that anyone that owns Magic cards can sign up to be a seller and anyone can be buyer. This is different from buying booster packs from Wizards of the Coast because you will know in advance which card you are buying, the price, and the condition of the card!</p>
    <p>Develop your collection cheaply and without gambling on boosters by using MTG-marketplace!</p>

    <h2>How do I buy?</h2>
    <p>To start buying on MTG-marketplace, simply follow these easy steps:</p>
    <ol>
        <li>The first step to buying a card is signing up. Click on the 'Profile' link in the top right of your screen to take you to the login/signup page. Without signing up for an account, you can only browse available listings, you cannot buy.</li>
        <li>Click 'Browse' in the top right to go to our listings page. You can filter the listings to find the cards you want.</li>
        <li>From the listings page, click on the image of the card you want. This takes you to the individual page for that card, where you can see all the listings, including the price and condition of each card.</li>
        <li>Once you have found the listing you want, click the Buy button to the right of the listing. This will take you to a confirmation page.</li>
        <li>Clicking the 'Confirm' button will take you to out of MTG-marketplace to our payment gateway Stripe, which will securely handle your payment information.</li>
        <li>Enter your credit card information and click 'Pay' and it's all done! The seller will be notified of the sale and your card will be sent.</li>
    </ol>

    <h2>How do I sell?</h2>
    <p>To start selling on MTG-marketplace, simply follow these easy steps:</p>
    <ol>
        <li>Sign up for an account by clicking the 'Profile' link in the top right, which will take you to our login/signup page.</li>
        <li>Go to the 'Profile' page.</li>
        <li>Click the 'Create new listing' button.</li>
        <li>Search for the card you wish to sell by entering its name and set. Then click the 'Search' button.</li>
        <li>Confirm that this is the card you wish to sell, or search again.</li>
        <li>Enter the price you wish to sell at and the condition of the card.</li>
        <li>That's it! Your card is now on the listings page for any other users to browse and buy.</li>
    </ol>

    <h2>What are the fees?</h2>
    <p>MTG-marketplace charges a fee of 5%.</p>
    <p>This means that if you purchase a card for $1, MTG-marketplace will take 5c and the seller will receive 95c.</p>

    <h2>Is it secure?</h2>
    <p>All payments on MTG-marketplace are handled by Stripe.</p>
    <p>Stripe provides payment processing for online businesses and handles billions of dollars worth of transactions each year. Stripe has been audited by a PCI-certified auditor and is certified to PCI Service Provider Level 1. This is the most stringent level of certification available in the payments industry. To accomplish this, Stripe makes use of best-in-class security tools and practices to maintain a high level of security at Stripe.</p> 
</div>